name: Terraform CI

on: 
  push:
    branches:
      - task

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
    - name: Check out code  
      uses: actions/checkout@v1
#       env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Run a Terraform init  
      uses: docker://hashicorp/terraform:0.15.3
      with:
        entrypoint: terraform
        args: init

    - name: Run a Terraform validate    
      uses: docker://hashicorp/terraform:0.15.3
      with:
        entrypoint: terraform
        args: validate
    
    - name: Set up Go 1.16.4
      uses: actions/setup-go@v1
      with:
        go-version: 1.16.4
      id: go

    - name: Get dependencies
      run: |
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        else
          go get -v -d -t ./...  
        fi
        
    - name: Create AWS creds file
      run: echo [default] >> awsCreds.txt;echo  AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" >> awsCreds.txt; echo AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> awsCreds.txt;cat awsCreds.txt

      
    - name: Test
      working-directory: /home/runner/work/terraformTask/terraformTask/test
      run: sudo go test -v

